### ISSUE TITLE
docs : readme.md 파일 정리하기

### ISSUE THREAD

**Issue by 2ood** [osamhack2021/app_web_IoT_UMCS_Team60#22]
* 프로젝트 이름
* 프로젝트 소개
* 기능 설명
* 컴퓨터 / 필수조건
* 기술 스택
* 설치 안내
* 프로젝트 사용법
* 팀 정보
* 저작권 및 사용권 정보

**Comment by namingsense** [comment]
![UMCS_system](https://user-images.githubusercontent.com/28801695/135297278-a9e6bc05-35f4-4896-ace6-8f75a90bd685.jpg)

**Comment by 2ood** [comment]
@mskim9967  IoT 도 설정할 것들 있으면 IoT/README.md 생성해서 추가 바랍니다.
@Wo-ogie 관리자 페이지도 설정할 것들 있으면 WEB/README.md 생성해서 추가 바랍니다.

**Comment by namingsense** [comment]
![UMCS_icon_with_round_back](https://user-images.githubusercontent.com/28801695/137841908-636ed207-54f2-4579-a7d4-2b1679a47ee4.png)

**Comment by namingsense** [comment]
![image](https://user-images.githubusercontent.com/28801695/137847123-5cbee7a3-98a5-42bc-b436-dfb87dc07816.png)
