### ISSUE TITLE
vue 웹페이지 연동 문제

### ISSUE THREAD

**Issue by namingsense** [osamhack2021/app_web_IoT_UMCS_Team60#89]
does not work properly without javascript enabled 라는 에러와 함께 진행 불가

**Comment by Wo-ogie** [comment]
# 문제 원인 분석

1. build한 html 파일에서 정적 파일(css, js 등)을 불러오지 못하는 문제
2. Vue router가 동작하지 않아 원하는 페이지가 전혀 보이지 않던 문제

<br>

# 문제 해결

1. vue build파일을 server/pubilc으로 저장하고 app.use(express.static(path.join(__dirname, ‘public’)));  사용해서 static파일들을 https://militaryumcs.com 경로로 가저오게 설정
2. vue router의 mode를 history에서 hash로 변경. 만약 history mode(URL에 "#"이 보이지 않는 mode)를 사용하고 싶다면 아래의 두 링크를 참고하여 설정해줘야 함.
>[Vue Router history mode - server setting](https://router.vuejs.org/kr/guide/essentials/history-mode.html#%E1%84%89%E1%85%A5%E1%84%87%E1%85%A5-%E1%84%89%E1%85%A5%E1%86%AF%E1%84%8C%E1%85%A5%E1%86%BC-%E1%84%8B%E1%85%A8%E1%84%8C%E1%85%A6)
>[connect-history-api-fallback 미들웨어](https://github.com/bripkens/connect-history-api-fallback)
